# Generated by Django 4.1.3 on 2023-02-14 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesforceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userid", models.CharField(max_length=100)),
                ("access_token", models.CharField(max_length=200, null=True)),
                ("refresh_token", models.CharField(max_length=200, null=True)),
                ("instance_url", models.CharField(max_length=200, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SegmentData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_uid", models.CharField(default=0, max_length=500)),
                ("to", models.EmailField(blank=True, max_length=254, null=True)),
                ("subject", models.CharField(blank=True, max_length=500, null=True)),
                ("city", models.CharField(blank=True, max_length=500, null=True)),
                ("region", models.CharField(blank=True, max_length=500, null=True)),
                ("country", models.CharField(blank=True, max_length=500, null=True)),
                ("openAt", models.DateTimeField()),
                (
                    "user_detail",
                    models.ForeignKey(
                        default=123,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.salesforcedata",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailTrack",
            fields=[
                (
                    "email_uid",
                    models.CharField(max_length=500, primary_key=True, serialize=False),
                ),
                ("to", models.EmailField(blank=True, max_length=254, null=True)),
                ("subject", models.CharField(blank=True, max_length=500, null=True)),
                ("clicks", models.IntegerField(default=0)),
                (
                    "user_detail",
                    models.ForeignKey(
                        default=123,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.salesforcedata",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailLinkTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link_name", models.CharField(max_length=500)),
                ("link_clicks", models.IntegerField(default=0)),
                ("clickedAt", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "email_track",
                    models.ForeignKey(
                        default=123,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.emailtrack",
                    ),
                ),
            ],
        ),
    ]
