# Generated by Django 4.1.3 on 2023-02-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_segmentdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="segmentdata",
            name="valid",
            field=models.IntegerField(default=1),
        ),
    ]
