# Generated by Django 4.1.3 on 2023-02-14 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_segmentdata_valid"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=500, null=True)),
                ("email_uid", models.CharField(blank=True, max_length=500, null=True)),
                ("to", models.EmailField(blank=True, max_length=254, null=True)),
                ("subject", models.CharField(blank=True, max_length=500, null=True)),
                ("city", models.CharField(blank=True, max_length=500, null=True)),
                ("region", models.CharField(blank=True, max_length=500, null=True)),
                ("country", models.CharField(blank=True, max_length=500, null=True)),
                ("openAt", models.DateTimeField()),
                ("link", models.CharField(blank=True, max_length=500, null=True)),
                ("valid", models.IntegerField(default=1)),
                (
                    "user_detail",
                    models.ForeignKey(
                        default=123,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.salesforcedata",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="SegmentData",
        ),
    ]
